# Generated by Django 6.1.1 on 2026-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expressao', models.CharField(max_length=255, verbose_name='Expressão')),
                ('resultado', models.CharField(max_length=255, verbose_name='Resultado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
